export const DISTRICTS_EN: Record<string, string> = {
  // 臺北市 (Taipei City)
  "松山區": "Songshan Dist.",
  "大安區": "Da'an Dist.",
  "中正區": "Zhongzheng Dist.",
  "萬華區": "Wanhua Dist.",
  "大同區": "Datong Dist.",
  "中山區": "Zhongshan Dist.",
  "文山區": "Wenshan Dist.",
  "南港區": "Nangang Dist.",
  "內湖區": "Neihu Dist.",
  "士林區": "Shilin Dist.",
  "北投區": "Beitou Dist.",
  "信義區": "Xinyi Dist.",

  // 新北市 (New Taipei City)
  "新莊區": "Xinzhuang Dist.",
  "林口區": "Linkou Dist.",
  "五股區": "Wugu Dist.",
  "蘆洲區": "Luzhou Dist.",
  "三重區": "Sanchong Dist.",
  "泰山區": "Taishan Dist.",
  "新店區": "Xindian Dist.",
  "石碇區": "Shiding Dist.",
  "深坑區": "Shenkeng Dist.",
  "坪林區": "Pinglin Dist.",
  "烏來區": "Wulai Dist.",
  "板橋區": "Banqiao Dist.",
  "三峽區": "Sanxia Dist.",
  "鶯歌區": "Yingge Dist.",
  "樹林區": "Shulin Dist.",
  "中和區": "Zhonghe Dist.",
  "土城區": "Tucheng Dist.",
  "瑞芳區": "Ruifang Dist.",
  "平溪區": "Pingxi Dist.",
  "雙溪區": "Shuangxi Dist.",
  "貢寮區": "Gongliao Dist.",
  "金山區": "Jinshan Dist.",
  "萬里區": "Wanli Dist.",
  "淡水區": "Tamsui Dist.",
  "汐止區": "Xizhi Dist.",
  "三芝區": "Sanzhi Dist.",
  "石門區": "Shimen Dist.",
  "八里區": "Bali Dist.",
  "永和區": "Yonghe Dist.",

  // 桃園市 (Taoyuan City)
  "桃園區": "Taoyuan Dist.",
  "大溪區": "Daxi Dist.",
  "中壢區": "Zhongli Dist.",
  "楊梅區": "Yangmei Dist.",
  "蘆竹區": "Luzhu Dist.",
  "大園區": "Dayuan Dist.",
  "龜山區": "Guishan Dist.",
  "八德區": "Bade Dist.",
  "龍潭區": "Longtan Dist.",
  "平鎮區": "Pingzhen Dist.",
  "新屋區": "Xinwu Dist.",
  "觀音區": "Guanyin Dist.",
  "復興區": "Fuxing Dist.",

  // 臺中市 (Taichung City)
  "中區": "Zhong Dist.",
  "東區": "East Dist.",
  "南區": "South Dist.",
  "西區": "West Dist.",
  "北區": "North Dist.",
  "西屯區": "Xitun Dist.",
  "南屯區": "Nantun Dist.",
  "北屯區": "Beitun Dist.",
  "豐原區": "Fengyuan Dist.",
  "東勢區": "Dongshi Dist.",
  "大甲區": "Dajia Dist.",
  "清水區": "Qingshui Dist.",
  "沙鹿區": "Shalu Dist.",
  "梧棲區": "Wuqi Dist.",
  "后里區": "Houli Dist.",
  "神岡區": "Shengang Dist.",
  "潭子區": "Tanzi Dist.",
  "大雅區": "Daya Dist.",
  "新社區": "Xinshe Dist.",
  "石岡區": "Shigang Dist.",
  "外埔區": "Waipu Dist.",
  // 大安區 already mapped above (Taipei); Taichung's is the same key
  "烏日區": "Wuri Dist.",
  "大肚區": "Dadu Dist.",
  "龍井區": "Longjing Dist.",
  "霧峰區": "Wufeng Dist.",
  "太平區": "Taiping Dist.",
  "大里區": "Dali Dist.",
  "和平區": "Heping Dist.",

  // 臺南市 (Tainan City)
  // 東區, 南區, 北區 already mapped above
  "安南區": "Annan Dist.",
  "安平區": "Anping Dist.",
  "中西區": "West Central Dist.",
  "新營區": "Xinying Dist.",
  "鹽水區": "Yanshui Dist.",
  "柳營區": "Liuying Dist.",
  "白河區": "Baihe Dist.",
  "後壁區": "Houbi Dist.",
  "東山區": "Dongshan Dist.",
  "麻豆區": "Madou Dist.",
  "下營區": "Xiaying Dist.",
  "六甲區": "Liujia Dist.",
  "官田區": "Guantian Dist.",
  "大內區": "Danei Dist.",
  "佳里區": "Jiali Dist.",
  "西港區": "Xigang Dist.",
  "七股區": "Qigu Dist.",
  "將軍區": "Jiangjun Dist.",
  "北門區": "Beimen Dist.",
  "學甲區": "Xuejia Dist.",
  "新化區": "Xinhua Dist.",
  "善化區": "Shanhua Dist.",
  "新市區": "Xinshi Dist.",
  "安定區": "Anding Dist.",
  "山上區": "Shanshang Dist.",
  "左鎮區": "Zuozhen Dist.",
  "仁德區": "Rende Dist.",
  "歸仁區": "Guiren Dist.",
  "關廟區": "Guanmiao Dist.",
  "龍崎區": "Longqi Dist.",
  "玉井區": "Yujing Dist.",
  "楠西區": "Nanxi Dist.",
  "南化區": "Nanhua Dist.",
  "永康區": "Yongkang Dist.",

  // 高雄市 (Kaohsiung City)
  "鹽埕區": "Yancheng Dist.",
  "鼓山區": "Gushan Dist.",
  "左營區": "Zuoying Dist.",
  "楠梓區": "Nanzi Dist.",
  "三民區": "Sanmin Dist.",
  "新興區": "Xinxing Dist.",
  "前金區": "Qianjin Dist.",
  "苓雅區": "Lingya Dist.",
  "前鎮區": "Qianzhen Dist.",
  "旗津區": "Cijin Dist.",
  "小港區": "Xiaogang Dist.",
  "鳳山區": "Fengshan Dist.",
  "林園區": "Linyuan Dist.",
  "大寮區": "Daliao Dist.",
  "大樹區": "Dashu Dist.",
  "大社區": "Dashe Dist.",
  "仁武區": "Renwu Dist.",
  "鳥松區": "Niaosong Dist.",
  "岡山區": "Gangshan Dist.",
  "橋頭區": "Qiaotou Dist.",
  "燕巢區": "Yanchao Dist.",
  "田寮區": "Tianliao Dist.",
  "阿蓮區": "Alian Dist.",
  "路竹區": "Luzhu Dist.",
  "湖內區": "Hunei Dist.",
  "茄萣區": "Qieding Dist.",
  "永安區": "Yong'an Dist.",
  "彌陀區": "Mituo Dist.",
  "梓官區": "Ziguan Dist.",
  "旗山區": "Qishan Dist.",
  "美濃區": "Meinong Dist.",
  "六龜區": "Liugui Dist.",
  "甲仙區": "Jiaxian Dist.",
  "杉林區": "Shanlin Dist.",
  "內門區": "Neimen Dist.",
  "茂林區": "Maolin Dist.",
  "桃源區": "Taoyuan Dist.",
  "那瑪夏區": "Namaxia Dist.",

  // 基隆市 (Keelung City)
  // 中正區, 中山區, 信義區 already mapped above
  "七堵區": "Qidu Dist.",
  "暖暖區": "Nuannuan Dist.",
  "仁愛區": "Ren'ai Dist.",
  "安樂區": "Anle Dist.",

  // 新竹市 (Hsinchu City)
  "新竹市": "Hsinchu City",

  // 嘉義市 (Chiayi City)
  "嘉義市": "Chiayi City",

  // 新竹縣 (Hsinchu County)
  "竹東鎮": "Zhudong Township",
  "關西鎮": "Guanxi Township",
  "新埔鎮": "Xinpu Township",
  "竹北市": "Zhubei City",
  "湖口鄉": "Hukou Township",
  "橫山鄉": "Hengshan Township",
  "新豐鄉": "Xinfeng Township",
  "芎林鄉": "Qionglin Township",
  "寶山鄉": "Baoshan Township",
  "北埔鄉": "Beipu Township",
  "峨眉鄉": "Emei Township",
  "尖石鄉": "Jianshi Township",
  "五峰鄉": "Wufeng Township",

  // 苗栗縣 (Miaoli County)
  "苗栗市": "Miaoli City",
  "苑裡鎮": "Yuanli Township",
  "通霄鎮": "Tongxiao Township",
  "公館鄉": "Gongguan Township",
  "銅鑼鄉": "Tongluo Township",
  "三義鄉": "Sanyi Township",
  "西湖鄉": "Xihu Township",
  "頭屋鄉": "Touwu Township",
  "竹南鎮": "Zhunan Township",
  "頭份市": "Toufen City",
  "造橋鄉": "Zaoqiao Township",
  "後龍鎮": "Houlong Township",
  "三灣鄉": "Sanwan Township",
  "南庄鄉": "Nanzhuang Township",
  "大湖鄉": "Dahu Township",
  "卓蘭鎮": "Zhuolan Township",
  "獅潭鄉": "Shitan Township",
  "泰安鄉": "Tai'an Township",

  // 彰化縣 (Changhua County)
  "彰化市": "Changhua City",
  "鹿港鎮": "Lukang Township",
  "和美鎮": "Hemei Township",
  "北斗鎮": "Beidou Township",
  "員林市": "Yuanlin City",
  "溪湖鎮": "Xihu Township",
  "田中鎮": "Tianzhong Township",
  "二林鎮": "Erlin Township",
  "線西鄉": "Xianxi Township",
  "伸港鄉": "Shengang Township",
  "福興鄉": "Fuxing Township",
  "秀水鄉": "Xiushui Township",
  "花壇鄉": "Huatan Township",
  "芬園鄉": "Fenyuan Township",
  "大村鄉": "Dacun Township",
  "埔鹽鄉": "Puyan Township",
  "埔心鄉": "Puxin Township",
  "永靖鄉": "Yongjing Township",
  "社頭鄉": "Shetou Township",
  "二水鄉": "Ershui Township",
  "田尾鄉": "Tianwei Township",
  "埤頭鄉": "Pitou Township",
  "芳苑鄉": "Fangyuan Township",
  "大城鄉": "Dacheng Township",
  "竹塘鄉": "Zhutang Township",
  "溪州鄉": "Xizhou Township",

  // 南投縣 (Nantou County)
  "南投市": "Nantou City",
  "埔里鎮": "Puli Township",
  "草屯鎮": "Caotun Township",
  "竹山鎮": "Zhushan Township",
  "集集鎮": "Jiji Township",
  "名間鄉": "Mingjian Township",
  "鹿谷鄉": "Lugu Township",
  "中寮鄉": "Zhongliao Township",
  "魚池鄉": "Yuchi Township",
  "國姓鄉": "Guoxing Township",
  "水里鄉": "Shuili Township",
  "信義鄉": "Xinyi Township",
  "仁愛鄉": "Ren'ai Township",

  // 雲林縣 (Yunlin County)
  "斗六市": "Douliu City",
  "斗南鎮": "Dounan Township",
  "虎尾鎮": "Huwei Township",
  "西螺鎮": "Xiluo Township",
  "土庫鎮": "Tuku Township",
  "北港鎮": "Beigang Township",
  "古坑鄉": "Gukeng Township",
  "大埤鄉": "Dapi Township",
  "莿桐鄉": "Citong Township",
  "林內鄉": "Linnei Township",
  "二崙鄉": "Erlun Township",
  "崙背鄉": "Lunbei Township",
  "麥寮鄉": "Mailiao Township",
  "東勢鄉": "Dongshi Township",
  "褒忠鄉": "Baozhong Township",
  "臺西鄉": "Taixi Township",
  "元長鄉": "Yuanchang Township",
  "四湖鄉": "Sihu Township",
  "口湖鄉": "Kouhu Township",
  "水林鄉": "Shuilin Township",

  // 嘉義縣 (Chiayi County)
  "朴子市": "Puzi City",
  "布袋鎮": "Budai Township",
  "大林鎮": "Dalin Township",
  "民雄鄉": "Minxiong Township",
  "溪口鄉": "Xikou Township",
  "新港鄉": "Xingang Township",
  "六腳鄉": "Liujiao Township",
  "東石鄉": "Dongshi Township",
  "義竹鄉": "Yizhu Township",
  "鹿草鄉": "Lucao Township",
  "太保市": "Taibao City",
  "水上鄉": "Shuishang Township",
  "中埔鄉": "Zhongpu Township",
  "竹崎鄉": "Zhuqi Township",
  "梅山鄉": "Meishan Township",
  "番路鄉": "Fanlu Township",
  "大埔鄉": "Dapu Township",
  "阿里山鄉": "Alishan Township",

  // 屏東縣 (Pingtung County)
  "屏東市": "Pingtung City",
  "潮州鎮": "Chaozhou Township",
  "東港鎮": "Donggang Township",
  "恆春鎮": "Hengchun Township",
  "萬丹鄉": "Wandan Township",
  "長治鄉": "Changzhi Township",
  "麟洛鄉": "Linluo Township",
  "九如鄉": "Jiuru Township",
  "里港鄉": "Ligang Township",
  "鹽埔鄉": "Yanpu Township",
  "高樹鄉": "Gaoshu Township",
  "萬巒鄉": "Wanluan Township",
  "內埔鄉": "Neipu Township",
  "竹田鄉": "Zhutian Township",
  "新埤鄉": "Xinpi Township",
  "枋寮鄉": "Fangliao Township",
  "新園鄉": "Xinyuan Township",
  "崁頂鄉": "Kanding Township",
  "林邊鄉": "Linbian Township",
  "南州鄉": "Nanzhou Township",
  "佳冬鄉": "Jiadong Township",
  "琉球鄉": "Liuqiu Township",
  "車城鄉": "Checheng Township",
  "滿州鄉": "Manzhou Township",
  "枋山鄉": "Fangshan Township",
  "三地門鄉": "Sandimen Township",
  "霧臺鄉": "Wutai Township",
  "瑪家鄉": "Majia Township",
  "泰武鄉": "Taiwu Township",
  "來義鄉": "Laiyi Township",
  "春日鄉": "Chunri Township",
  "獅子鄉": "Shizi Township",
  "牡丹鄉": "Mudan Township",

  // 宜蘭縣 (Yilan County)
  "宜蘭市": "Yilan City",
  "頭城鎮": "Toucheng Township",
  "礁溪鄉": "Jiaoxi Township",
  "壯圍鄉": "Zhuangwei Township",
  "員山鄉": "Yuanshan Township",
  "羅東鎮": "Luodong Township",
  "五結鄉": "Wujie Township",
  "冬山鄉": "Dongshan Township",
  "蘇澳鎮": "Su'ao Township",
  "三星鄉": "Sanxing Township",
  "大同鄉": "Datong Township",
  "南澳鄉": "Nan'ao Township",

  // 花蓮縣 (Hualien County)
  "花蓮市": "Hualien City",
  "光復鄉": "Guangfu Township",
  "玉里鎮": "Yuli Township",
  "新城鄉": "Xincheng Township",
  "吉安鄉": "Ji'an Township",
  "壽豐鄉": "Shoufeng Township",
  "鳳林鎮": "Fenglin Township",
  "豐濱鄉": "Fengbin Township",
  "瑞穗鄉": "Ruisui Township",
  "富里鄉": "Fuli Township",
  "秀林鄉": "Xiulin Township",
  "萬榮鄉": "Wanrong Township",
  "卓溪鄉": "Zhuoxi Township",

  // 臺東縣 (Taitung County)
  "臺東市": "Taitung City",
  "成功鎮": "Chenggong Township",
  "關山鎮": "Guanshan Township",
  "卑南鄉": "Beinan Township",
  "大武鄉": "Dawu Township",
  "太麻里鄉": "Taimali Township",
  "東河鄉": "Donghe Township",
  "長濱鄉": "Changbin Township",
  "鹿野鄉": "Luye Township",
  "池上鄉": "Chishang Township",
  "綠島鄉": "Ludao Township",
  "延平鄉": "Yanping Township",
  "海端鄉": "Haiduan Township",
  "達仁鄉": "Daren Township",
  "金峰鄉": "Jinfeng Township",
  "蘭嶼鄉": "Lanyu Township",

  // 澎湖縣 (Penghu County)
  "馬公市": "Magong City",
  "湖西鄉": "Huxi Township",
  "白沙鄉": "Baisha Township",
  "西嶼鄉": "Xiyu Township",
  "望安鄉": "Wang'an Township",
  "七美鄉": "Qimei Township",

  // 金門縣 (Kinmen County)
  "金湖鎮": "Jinhu Township",
  "金沙鎮": "Jinsha Township",
  "金城鎮": "Jincheng Township",
  "金寧鄉": "Jinning Township",
  "烈嶼鄉": "Lieyu Township",
  "烏坵鄉": "Wuqiu Township",

  // 連江縣 (Lienchiang County / Matsu)
  "南竿鄉": "Nangan Township",
  "北竿鄉": "Beigan Township",
  "莒光鄉": "Juguang Township",
  "東引鄉": "Dongyin Township",
}
